/**
 * Well-known IMAP/SMTP settings for mail hosting.
 * Gmail OAuth (recommended) lives on the Gmail tab; Gmail here uses IMAP + App Password.
 */

export type AppPasswordGuide = {
  alertTitle: string;
  intro: string;
  linkHref: string;
  linkLabel: string;
  linkSuffix?: string;
  footnote?: string;
  emailPlaceholder: string;
  passwordFieldLabel: string;
  passwordPlaceholder: string;
  passwordHint: string;
};

export type MailProviderPreset = {
  id: string;
  label: string;
  /** Shown under the selector */
  hint?: string;
  /** When set, Add Account shows an app-password alert + tailored password field copy */
  appPasswordGuide?: AppPasswordGuide;
  imap_host: string;
  imap_port: number;
  imap_use_tls: boolean;
  smtp_host: string;
  smtp_port: number;
 /** Mirrors AddAccountDialog: true = implicit SSL (465), false = STARTTLS-style (587) */
  smtp_use_tls: boolean;
};

/** Sentinel values for the provider Select (not real presets). */
export const MAIL_PRESET_NONE = "none";
export const MAIL_PRESET_CUSTOM = "custom";

export const MAIL_PRESET_GMAIL = "gmail";
export const MAIL_PRESET_YAHOO = "yahoo";

const GMAIL_APP_PASSWORD_GUIDE: AppPasswordGuide = {
  alertTitle: "Gmail needs an App Password",
  intro:
    "Your normal Google password won't work here. Create a 16-character App Password in your Google Account, then paste it below.",
  linkHref: "https://myaccount.google.com/apppasswords",
  linkLabel: "Create an App Password at Google",
  linkSuffix: "(turn on 2-Step Verification first if asked).",
  footnote: "Prefer the Google sign-in popup? Use the Gmail tab instead.",
  emailPlaceholder: "you@gmail.com",
  passwordFieldLabel: "App Password",
  passwordPlaceholder: "16-character code from Google",
  passwordHint: "Paste the 16-character code from Google — spaces are removed automatically.",
};

const YAHOO_APP_PASSWORD_GUIDE: AppPasswordGuide = {
  alertTitle: "Yahoo needs an App Password",
  intro:
    "Your normal Yahoo password won't work here. Under External connections, create an app password for Unified Inbox Hub, then paste it below.",
  linkHref: "https://login.yahoo.com/account/security",
  linkLabel: "Open Yahoo Account Security",
  linkSuffix: "(then choose Create app password under External connections).",
  footnote:
    "Use a normal browser window where you're already signed into Yahoo — private/incognito mode may block app password creation.",
  emailPlaceholder: "you@yahoo.com",
  passwordFieldLabel: "App Password",
  passwordPlaceholder: "Password generated by Yahoo",
  passwordHint:
    "Paste the app password from Yahoo — spaces are removed automatically. IMAP must be enabled for your Yahoo account.",
};

const ICLOUD_APP_PASSWORD_GUIDE: AppPasswordGuide = {
  alertTitle: "iCloud needs an app-specific password",
  intro:
    "Your Apple ID password won't work here. Generate an app-specific password in your Apple Account, then paste it below.",
  linkHref: "https://account.apple.com/account/manage",
  linkLabel: "Manage your Apple Account",
  linkSuffix: "(Sign-In and Security → App-Specific Passwords).",
  emailPlaceholder: "you@icloud.com",
  passwordFieldLabel: "App-Specific Password",
  passwordPlaceholder: "Password generated by Apple",
  passwordHint: "Paste the app-specific password from Apple — spaces are removed automatically.",
};

const HOSTINGER_SETUP_GUIDE: AppPasswordGuide = {
  alertTitle: "Hostinger Email setup",
  intro:
    "Use your full @yourdomain.com address and the same password as Hostinger webmail (hPanel → Emails). IMAP is enabled by default on Hostinger Email.",
  linkHref: "https://www.hostinger.com/support/1575756-how-to-get-email-account-configuration-details-for-hostinger-email",
  linkLabel: "View Hostinger IMAP settings",
  linkSuffix: "(imap.hostinger.com, port 993, SSL).",
  footnote:
    "If connection fails, your mailbox may be on Titan Mail instead — choose Titan Mail from the provider list.",
  emailPlaceholder: "you@yourdomain.com",
  passwordFieldLabel: "Mailbox password",
  passwordPlaceholder: "Same password as Hostinger webmail",
  passwordHint: "Use the password from hPanel / mail.hostinger.com — not your Hostinger login password unless they match.",
};

const TITAN_SETUP_GUIDE: AppPasswordGuide = {
  alertTitle: "Enable Titan for other apps first",
  intro:
    "Titan blocks IMAP until you allow third-party email apps. Sign in to Titan webmail, open Settings (gear) → Enable Titan on other apps, then paste your mailbox password below.",
  linkHref: "https://support.titan.email/hc/en-us/articles/25005307786905-Enable-Titan-on-other-apps",
  linkLabel: "How to enable Titan on other apps",
  linkSuffix: "(required before IMAP will work).",
  footnote:
    "Two-factor authentication (2FA) must be turned OFF on Titan — it blocks IMAP. Use your Titan mailbox password, not an app password.",
  emailPlaceholder: "you@yourdomain.com",
  passwordFieldLabel: "Mailbox password",
  passwordPlaceholder: "Your Titan webmail password",
  passwordHint:
    "After enabling third-party access in Titan webmail, use your normal mailbox password here.",
};

export const MAIL_PRESET_HOSTINGER = "hostinger";
export const MAIL_PRESET_TITAN = "titan";

export const MAIL_PROVIDER_PRESETS: MailProviderPreset[] = [
  {
    id: MAIL_PRESET_GMAIL,
    label: "Gmail",
    hint: "Sign in with a Google App Password (16 characters)",
    appPasswordGuide: GMAIL_APP_PASSWORD_GUIDE,
    imap_host: "imap.gmail.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.gmail.com",
    smtp_port: 587,
    smtp_use_tls: false,
  },
  {
    id: MAIL_PRESET_HOSTINGER,
    label: "Hostinger Email",
    hint: "Standard Hostinger mail — imap.hostinger.com",
    appPasswordGuide: HOSTINGER_SETUP_GUIDE,
    imap_host: "imap.hostinger.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.hostinger.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: MAIL_PRESET_TITAN,
    label: "Titan Mail",
    hint: "Enable “Titan on other apps” in webmail first",
    appPasswordGuide: TITAN_SETUP_GUIDE,
    imap_host: "imap.titan.email",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.titan.email",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "microsoft365",
    label: "Microsoft 365 / Outlook",
    hint: "Work, school, or @outlook.com / @hotmail.com",
    imap_host: "outlook.office365.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.office365.com",
    smtp_port: 587,
    smtp_use_tls: false,
  },
  {
    id: "rackspace",
    label: "Rackspace Email",
    imap_host: "secure.emailsrvr.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "secure.emailsrvr.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "godaddy",
    label: "GoDaddy",
    imap_host: "imap.secureserver.net",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtpout.secureserver.net",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "zoho",
    label: "Zoho Mail",
    imap_host: "imap.zoho.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.zoho.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: MAIL_PRESET_YAHOO,
    label: "Yahoo Mail",
    hint: "Requires a Yahoo App Password — not your normal login password",
    appPasswordGuide: YAHOO_APP_PASSWORD_GUIDE,
    imap_host: "imap.mail.yahoo.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.mail.yahoo.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "fastmail",
    label: "Fastmail",
    imap_host: "imap.fastmail.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.fastmail.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "ionos",
    label: "IONOS",
    imap_host: "imap.ionos.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.ionos.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "namecheap",
    label: "Namecheap Private Email",
    imap_host: "mail.privateemail.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "mail.privateemail.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
  {
    id: "icloud",
    label: "iCloud Mail",
    hint: "Use an app-specific password from Apple ID settings",
    appPasswordGuide: ICLOUD_APP_PASSWORD_GUIDE,
    imap_host: "imap.mail.me.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.mail.me.com",
    smtp_port: 587,
    smtp_use_tls: false,
  },
  {
    id: "dreamhost",
    label: "DreamHost",
    imap_host: "imap.dreamhost.com",
    imap_port: 993,
    imap_use_tls: true,
    smtp_host: "smtp.dreamhost.com",
    smtp_port: 465,
    smtp_use_tls: true,
  },
];

export function getMailProviderPreset(id: string): MailProviderPreset | undefined {
  return MAIL_PROVIDER_PRESETS.find((p) => p.id === id);
}

/** If current IMAP+SMTP hosts match a known preset, return its id (else `none`). */
export function matchMailProviderPresetFromHosts(imapHost: string, smtpHost: string): string {
  const ih = imapHost.trim().toLowerCase();
  const sh = smtpHost.trim().toLowerCase();
  if (!ih || !sh) return MAIL_PRESET_NONE;
  const hit = MAIL_PROVIDER_PRESETS.find(
    (p) => p.imap_host.toLowerCase() === ih && p.smtp_host.toLowerCase() === sh,
  );
  return hit?.id ?? MAIL_PRESET_NONE;
}
