project_id = "wunaudeomnobojbpoprv"

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.cron-sync-all]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false

[functions.imap-sync]
verify_jwt = false
